import Head from 'next/head';
import axios from 'axios';
import { useState } from 'react';
import { BsSearch } from 'react-icons/bs';
import Image from 'next/legacy/image';
import Forest from '../public/Forest.jpg';


export default function Home() {

  const [city, setCity] = useState("");

  const [weather, setWeather] = useState({});

  const [loading, setLoading] = useState(false);

  const url = `https://api.openweathermap.org/data/2.5/weather?q=bristol&units=metric&appid=${process.env.NEXT_PUBLIC_WEATHER_KEY}`

  const fetchWeather = (e) => {
    e.preventDefault()
    setLoading(true)
    axios.get(url).then((response) => {
      setWeather(response.data)
      console.log(response.data)
    })
    setCity("")
    setLoading(false)
  }

  return (
    <>
      <Head>
        <title>weather_app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="absolute top-0 left-0 right-0 bottom-0 bg-black/40 z-[1]" />

      <Image
        src={Forest}
        layout="fill"
        className="object-cover"
      />


    </>
  )
}
