import Head from 'next/head';
import axios from 'axios';
import { useState } from 'react';
import { BsSearch } from 'react-icons/bs';

export default function Home() {

  const [city, setCity] = useState("");

  const [weather, setWeather] = useState({});

  const [loading, setLoading] = useState(false);

  const url = `https://api.openweathermap.org/data/2.5/weather?q=bristol&appid=${process.env.NEXT_PUBLIC_WEATHER_KEY}`

  return (
    <>
      <Head>
        <title>weather_app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    
    </>
  )
}
